name: manage-azure-policy-efbf05e4
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'initiatives/NIST_SP_800-53_Rev._5_-_Security_Control_Baseline_-_Low_-_Selected_907e8b1eb62947a7bb1ad460/**'
#      - .github/workflows/manage-azure-policy-efbf05e4.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_efbf05e4}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          initiatives/NIST_SP_800-53_Rev._5_-_Security_Control_Baseline_-_Low_-_Selected_907e8b1eb62947a7bb1ad460/**
